
pipeline {
    agent any 
    stages {
        stage('checkout SCM') { 
            steps {
                git branch: 'main', url: 'https://github.com/nagcloudlab/repo1'
            }
        }
        stage('Install dependencies') { 
          steps {
                dir('ui-app') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') { 
            steps {
                sh 'echo "test"'
            }
        }
        stage('Build') { 
            steps {
                dir('ui-app') {
                    sh 'npm run build'
                }
            }
        }
        stage('Deploy') { 
            steps {
                dir('ui-app') {
                    sh "scp -r ./build/ ubuntu@15.207.248.121:/var/www/ui-app/"
                }
            }
        }
    }
}